// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['services']['appService']['GetAppInfo']();
}

export function GetCompressOptions() {
  return window['go']['services']['appService']['GetCompressOptions']();
}

export function GetIsAlwaysOnTop() {
  return window['go']['services']['appService']['GetIsAlwaysOnTop']();
}

export function GetLocalPosition() {
  return window['go']['services']['appService']['GetLocalPosition']();
}

export function GetWindowSize() {
  return window['go']['services']['appService']['GetWindowSize']();
}

export function SaveBoundary() {
  return window['go']['services']['appService']['SaveBoundary']();
}

export function SetIsAlwaysOnTop(arg1) {
  return window['go']['services']['appService']['SetIsAlwaysOnTop'](arg1);
}

export function Setup(arg1) {
  return window['go']['services']['appService']['Setup'](arg1);
}

export function UpdateCompressOptions(arg1) {
  return window['go']['services']['appService']['UpdateCompressOptions'](arg1);
}
