// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CompressImage(arg1:types.ImageFileInfo,arg2:types.CompressOptions):Promise<types.CompressResult>;

export function OpenFile(arg1:string):Promise<types.JSResp>;

export function OpenSelectFilesDialog():Promise<types.JSResp>;

export function ParseFilePaths(arg1:Array<string>):Promise<Array<types.ImageFileInfo>>;

export function RestoreImage(arg1:types.CompressResult):Promise<types.JSResp>;

export function Setup(arg1:context.Context):Promise<void>;
