// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressImages(arg1, arg2) {
  return window['go']['services']['fileService']['CompressImages'](arg1, arg2);
}

export function OpenSelectFilesDialog() {
  return window['go']['services']['fileService']['OpenSelectFilesDialog']();
}

export function Setup(arg1) {
  return window['go']['services']['fileService']['Setup'](arg1);
}
