// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressImage(arg1, arg2) {
  return window['go']['services']['fileService']['CompressImage'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['services']['fileService']['OpenFile'](arg1);
}

export function OpenSelectFilesDialog() {
  return window['go']['services']['fileService']['OpenSelectFilesDialog']();
}

export function ParseFilePaths(arg1) {
  return window['go']['services']['fileService']['ParseFilePaths'](arg1);
}

export function RestoreImage(arg1) {
  return window['go']['services']['fileService']['RestoreImage'](arg1);
}

export function Setup(arg1) {
  return window['go']['services']['fileService']['Setup'](arg1);
}
