// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function CompressImages(arg1:Array<string>,arg2:types.CompressOptions):Promise<types.JSResp>;

export function OpenSelectFilesDialog():Promise<types.JSResp>;

export function Setup(arg1:context.Context):Promise<void>;
