// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function GetAppInfo():Promise<types.JsObject>;

export function GetIsAllowsOnTop():Promise<boolean>;

export function SetIsAllowsOnTop(arg1:boolean):Promise<void>;

export function Setup(arg1:context.Context):Promise<void>;
