// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['services']['systimeService']['GetAppInfo']();
}

export function GetIsAllowsOnTop() {
  return window['go']['services']['systimeService']['GetIsAllowsOnTop']();
}

export function SetIsAllowsOnTop(arg1) {
  return window['go']['services']['systimeService']['SetIsAllowsOnTop'](arg1);
}

export function Setup(arg1) {
  return window['go']['services']['systimeService']['Setup'](arg1);
}
